### ISSUE TITLE
/v1/rearrangement facets issue...

### ISSUE THREAD

**Issue by bcorrie** [airr-community/adc-api-js-mongodb#1]
Hi @schristley 

The following query to /v1/rearrangements has an issue I believe:

```
{
    "filters": {
        "op":"=",
        "content": {
            "field":"repertoire_id",
            "value":"5168912186246295065-242ac11c-0001-012"
        }
    },
    "facets":"repertoire_id"
}
```
If the above is in the file samples-step2.json then the following curl: 

``` curl -s --data @samples-step2.json https://vdjserver.org/airr/v1/rearrangement```

returns:

```
    "Rearrangement": [
        {
            "_id": "5168912186246295065-242ac11c-0001-012",
            "count": 13527
        }
    ]
```
In the rearrangement response this has the field as the Mongo identifier "_id" rather than the field "repertoire_id" as it should.

**Comment by schristley** [comment]
fixed on master
